### ISSUE TITLE
Possible to have dark title-bar for Emacs?

### ISSUE THREAD

**Issue by ianyepan** [hubisan/emacs-wsl#16]
As titled, I have Emacs set up in WSL with X11 GUI. However, the title bar is currently white (as it is in your screenshot) -- I was wondering if it's possible to change it dark-mode somehow. Is this controlled by X11 and Windows10?

**Comment by hubisan** [comment]
Looks like this is controlled by windows 10 and for some reason the dark theme is not applied to that window.

This looks like a possible solution (not tried it) as I can't change the registry at work:
[How to get dark theme title bars in Windows 10, without changing your accent colour](https://www.onmsft.com/how-to/how-to-get-dark-theme-title-bars-in-windows-10-without-changing-your-accent-colour)

**Comment by ianyepan** [comment]
I just tried it now -- and even though it works, it does seem a bit hacky. Plus there's "no" option to "not" enable the accent window borders at the same time -- which I prefer to not enable.
Still, thanks for exposing this option to me. Great write-up btw, I've forwarded this repo for whomever comes to me asking about developing on Windows10 and WSL!
