### ISSUE TITLE
The feature branch still installs Emacs 26.3 in README (27.1 is out)

### ISSUE THREAD

**Issue by ianyepan** [hubisan/emacs-wsl#29]
As titled, a small reminder: you changed the master readme in #26 but seems to have forgotten to change the emacs version in your feature branch's readme as well.

**Comment by hubisan** [comment]
True. Started to work on this until I found out that snap doesn't work yet.

Going to remove that branch and add the relevant part to the issue #22.

**Comment by hubisan** [comment]
Branch deleted, closing.

**Comment by ianyepan** [comment]
Oh damn, I was using the `emacs-27.sh` file in that branch. Plan to move it to master as well?

**Comment by hubisan** [comment]
@ianpan870102 Added script file.

**Comment by ianyepan** [comment]
@hubisan Cheers!
