### ISSUE TITLE
add instructions for WSL2

### ISSUE THREAD

**Issue by hubisan** [hubisan/emacs-wsl#3]
Will adapt README.org once WSL2 it for non-insiders as well 
(Update 25.09.2020: got access WSL2 on one computer, will have a go and try to get this working)

TODOs from everything in here so far:

- [ ] Add https://docs.microsoft.com/en-us/windows/wsl/install-win10 and adapt instructions.

- [ ] Have to go through the installation (or check a video or the ms documentation) with WSL and WSL2 to see if it does setup a user for you and sets it as default user. Adapt the documentation accordingly. Looks like it does - https://www.youtube.com/watch?v=RTATnSA47Ak

- [ ] Add the best way to connect to the DISPLAY for WSL2. There are multiple solutions in https://github.com/microsoft/WSL/issues/4619:

  - The last comment https://github.com/microsoft/WSL/issues/4793#issuecomment-609429150 looks promising and is fully documented at https://github.com/famelis/wsl2-x11. Hmm, got changed, has access control now disabled as well.

  - Another secure solution from https://github.com/microsoft/WSL/issues/4793#issuecomment-607479461 and then https://github.com/cascadium/wsl-windows-toolbar-launcher#troubleshooting

  - Or the not so safe way (not quite sure about the consequences) by just disabling the access control in VcXsrv https://github.com/microsoft/WSL/issues/4793#issuecomment-577232999 and then to set the display automatically use `export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0`. In the comment it is done manually.

  - This [SOF answer](https://stackoverflow.com/a/61110604/1365754) tells you how to add a firewall rule. https://stackoverflow.com/a/61110604/1365754 The IP address is not working for me, probably have to use the one from resolv.conf.

  - This [SOF answer](https://stackoverflow.com/a/61110604/1365754) use another approach for the IP (in comments) as resolv.conf can have muliple IPs it seems. `export DISPLAY=$(ip route  | awk '/default via / {print $3; exit}' 2>/dev/null):0`

  - Already existing Windows Firewall Rules need to be checked. There might be one automatically created blocking VcXsrv.

- [ ] Add a troubleshooting section
  - The [post](https://www.reddit.com/r/emacs/comments/er248t/installing_emacs_on_wsl2_with_windows_but_it_works/) touches a few problems that might occur. Could add problems and solutions to the FAQ or make a new section for it. Following problems and solutions are mentioned: blurry screen or blurred images, fragmented disk error.
  - The solution of the memory issue (microsoft/WSL#4166) is critical.  

- [ ] Add a troubleshooting section
  - The [post](https://www.reddit.com/r/emacs/comments/er248t/installing_emacs_on_wsl2_with_windows_but_it_works/) touches a few problems that might occur. Could add problems and solutions to the FAQ or make a new section for it. Following problems and solutions are mentioned: blurry screen or blurred images, fragmented disk error.
  - The solution of the memory issue (microsoft/WSL#4166) is critical.

- [ ] Update FAQ
  - Instructing how to move the storage in WSL2 to another disk (MicrosoftDocs/WSL#412) is very useful (for me).

Helpful links to set up up WSL2:

- https://docs.microsoft.com/en-us/windows/wsl/wsl2-install
- https://autoize.com/xfce4-desktop-environment-and-x-server-for-ubuntu-on-wsl-2/
- https://www.reddit.com/r/emacs/comments/er248t/installing_emacs_on_wsl2_with_windows_but_it_works/
- https://github.com/microsoft/WSL/issues/4619
- https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes
- https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq

**Comment by psmith1303** [comment]
I forgot where I found this solution for the IP address under WSL2, but it works for me.

```
#
# Set up the DISPLAY for emacs
#
export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0
#
# Setup HOME for emacs
#
export HOME=/mnt/c/Users/psmith/
cd $HOME

```
That said, one also need to run the X server so it accepts non-local connections, and change Windows Defender firewall to. I did a gross 'hack' and just turned it off the Public firewall.

**Comment by hubisan** [comment]
Thanks for the input. Don't have the need and time to try WSL2 atm.

Here is a link to setup the firewall it seems to make it secure:
https://github.com/microsoft/WSL/issues/4106#issuecomment-608492570

**Comment by hubisan** [comment]
Another link that helps with WSL2 setup:
[post on reddit > Installing emacs on WSL2 with Windows, but it works](https://www.reddit.com/r/emacs/comments/er248t/installing_emacs_on_wsl2_with_windows_but_it_works/)

To properly connect the access control in VcXsrv is diabled (option -ac) so you don't have to touch the firewall settings. As mentionned this is not super safe:

> Let's download VcXsrv to provide the GUI, install it ; launch it and accept the default setup, upon reaching the extra settings, complete it with the last box ticked as well, like this. I know it's not super safe. This allows WSL2 to connect properly though, per this issue and this github.

Looks like WSL makes a user for you now the first time it is started and probably sets it as default user:

> Once WSL is installed, I launch it and it prompts for a username and password, I oblige.

- **TODO** Have to go through the installation with WSL and WSL2 to see if it does setup a user for you and adapt the documentation accordingly.
- **TODO** The post touches a few problems that might occur. Could add them to the FAQ or make a new section for problems you might encounter and the solution for it. Following problems and solutions are mentioned: blurry screen or blurred images, fragmented disk error.

**Comment by Adriankhl** [comment]
I am trying to use emacs in WSL2. A few comments about this page:

1. Why do you recommend installing lxde desktop? You don't need a desktop environment to run emacs.

2. Instructing how to move the storage in WSL2 to another disk (https://github.com/MicrosoftDocs/WSL/issues/412) is very useful (for me). 

3. The solution of the memory issue (https://github.com/microsoft/WSL/issues/4166) is critical.

4. I realized that everyone is recommending vcxsrv, and almost no discussion about Cygwin/X which (I believe) the vcxsrv is based on. However, `XWin` could provide some advantages (https://github.com/mviereck/runx), note that the script there doesn't work for me. It is not hard to setup, just install Cygwin (I use `scoop`) and run the setup again to install `xinit`.  Then run something like `cygwin.exe -c "XWin :0 -listen tcp -retro -lesspointer -multiwindow -clipboard -ac -wgl"&`  to start the XWindows. At first glance, emacs feels equally smooth. Maybe a benchmark is useful to distinguish between the two.

**Comment by hubisan** [comment]
@Adriankhl Thanks for your inputs.

Will be adding instructions for cygwin/x and remove the desktop installation part (made two new issues).

Will be adding WSL2 instructions once it is available to non-insiders. Hopefully the memory leakage will be fix by then. If not I will be adding it.

**Comment by ianyepan** [comment]
I had some trouble setting up X server for WSL2. Now that I solved it, thought I might contribute to this thread.
So this is the reddit thread that helped me: https://github.com/microsoft/WSL/issues/4106
The TL;DR is, set DISPLAY to include the IP address of the host, and don't forget to pass `-ac` flag/argument when launching Vcxsrv.

**Comment by lgrosz** [comment]
The stuff I had to do to get it working on WSL2 was

* Install vcxsrv, run with the -ac command
* Run `export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0` on WSL2
* Run the "Incoming Connections" trouble shooter on Windows after trying to run something graphical on WSL2

That last bit was the last hurdle for me, and I can't believe a Windows trouble shooter worked for once.
