### ISSUE TITLE
Consider passing the --with-modules flag to ./configure

### ISSUE THREAD

**Issue by ianyepan** [hubisan/emacs-wsl#30]
As titled, I think it's best to pass the `--with-modules` flag to `./configure`, which is crucial for users who want to experience packages like vterm. I understand that the `--with-json` flag is no longer necessary because it is the default behaviour.

**Comment by hubisan** [comment]
Should be the same for `--with-modules`:

https://www.gnu.org/savannah-checkouts/gnu/emacs/news/NEWS.27.1

> ** Emacs now builds with dynamic module support by default.
> Pass '--without-modules' to 'configure' to disable dynamic module
> support.

Do you know how to test if it has been installed with the flag?

**Comment by hubisan** [comment]
Tried vterm in Emacs 27.1 which as far as I understand only works if Emacs was configured with the `--with-modules` flag.
It works. Had to install CMake from Source and libtool-bin.

**Comment by ianyepan** [comment]
> Do you know how to test if it has been installed with the flag?

Installing vterm is the only way I can think of to test the modules support. It seems like both `--with-modules` and `--with-json` are enabled by default? Feel free to close this issue if that's the case.

**Comment by hubisan** [comment]
The configured features can be found in the variable `system-configuration-features`. 

This is the output for for Emacs 27.1:

```
XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
```

So it is definitely turned on. Closing this issue.
