### ISSUE TITLE
Why not install through PPA?

### ISSUE THREAD

**Issue by MC-Escherichia** [hubisan/emacs-wsl#39]
I was wondering if you considered having the install guide use the emacs 27.1 builds available in [kelleyk's ppa](https://launchpad.net/~kelleyk/+archive/ubuntu/emacs)? 

Is there a disadvantage to going this route? Thanks for putting this together it made the X-Server stuff a lot clearer to me.

**Comment by hubisan** [comment]
Was using the ppa back in the days. Can't remember why I stopped doing so.

Did you install it from the ppa? Does it work? If it does I will add it to the guide.

**Comment by MC-Escherichia** [comment]
I am able to run the PPA version through vcvxsrv. I will check back in a few days to confirm it doesn't have any hitches.

**Comment by ianyepan** [comment]
This PPA stopped uploading last September. The emacs version you'll get from the PPA would be only 27.1, while the current stable is already at 27.2.
IMO, building it yourself is better.

**Comment by hubisan** [comment]
Decided to not add the PPA. 

Building it yourself is straight forward and fast. And as @ianpan870102 pointed out the best way to guarantee that you get the newest stable version (or to choose an older version). And you can change the configuration, like remove `cairo` or add another option.
