### ISSUE TITLE
For the Install Ubuntu part state that Powershell 7+ won't work

### ISSUE THREAD

**Issue by frenchiveruti** [hubisan/emacs-wsl#44]
Hello, on windows there's PS5 (built-in) and PS7+ (upgraded version downloaded externally), the `Add-AppxPackage` command **only** works with PS5 (built-in)

**Comment by hubisan** [comment]
Should I just add a remark in the README that PS5 has to be used?

Seems that this is an unresolved [issue](https://github.com/PowerShell/PowerShell/issues/13138) with PS7. Should work with importing the module as follows (proposed in the issue). Can't verify this as not using PS7:

```
Import-Module -Name Appx -UseWindowsPowerShell
```

Or like this with surpressing warnings:

```
Import-Module -Name Appx -UseWindowsPowerShell -WarningAction SilentlyContinue
```

**Comment by frenchiveruti** [comment]
I would say just put it as a remark as it's not a big issue to just open PS5.
