### ISSUE TITLE
Run ansi-term inside Emacs

### ISSUE THREAD

**Issue by jcubic** [hubisan/emacs-wsl#8]
Is ansi-term and bash works in Emacs with this setup? I have GNU Emacs installed outside of WSL (from choco repository) and I have access to windows files from Linux but was not able to run bash in ansi-term inside Emacs.

**Comment by hubisan** [comment]
Ansi-term works (here with using zsh):

![image](https://user-images.githubusercontent.com/4160043/78678976-eef57c00-78e9-11ea-8952-0c9e2c978384.png)

Haven't used it a lot so far, so not sure if there are any downsides to it.
